plugins {
    id 'com.github.davidmc24.gradle.plugin.avro' version '1.2.0'
    id 'java'
    id 'application'
}

application {
    mainClassName = 'clients.Producer'
}

repositories {
    mavenCentral()
    maven {
        url "http://packages.confluent.io/maven/"
        allowInsecureProtocol = true
    }
}

sourceCompatibility = 11
targetCompatibility = 11

dependencies {
    implementation group: 'org.apache.kafka', name: 'kafka-clients', version: '2.6.0'
    implementation group: 'io.confluent', name: 'monitoring-interceptors', version: '6.0.0'

    implementation group: 'org.apache.avro', name: 'avro', version: '1.9.1'
    implementation group: 'org.apache.avro', name: 'avro-tools', version: '1.9.1'
    implementation group: 'io.confluent', name: 'kafka-avro-serializer', version: '6.0.0'

    implementation group: 'org.slf4j', name: 'slf4j-log4j12', version: '1.7.30'
}
